
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator

  #因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher，修改mvc路径匹配
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  boot:
    admin:
      client:
        port: 36003
        #连接监控服务端的地址，也就是actuator的服务端的运行ip 端口
        url: http://localhost:${spring.boot.admin.client.port}
        username: admin
        password: 123456

#swagger配置
springfox:
  documentation:
    enabled: true

#springboot监控Actuator
#监控中心服务端配置：打开所有节点监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

  #访问/acurator/health时显示完整信息
  endpoint:
    health:
      show-details: always
      enabled: true
    loggers:
      enabled: true
    logfile:
      external-file: /apps/logs/admin/auth.log
